// <auto-generated />
namespace Diagnostic_Center_Bill_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newcolumnpaymentstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newcolumnpaymentstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202107141635491_new column payment status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
