// <auto-generated />
namespace Diagnostic_Center_Bill_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class crateee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crateee));
        
        string IMigrationMetadata.Id
        {
            get { return "202107140400392_crateee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
